/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as GTokenRouteImport } from './routes/g/$token'
import { Route as DemoStadRouteImport } from './routes/demo/stad'
import { Route as DemoRapporterRouteImport } from './routes/demo/rapporter'
import { Route as DemoPresentkortRouteImport } from './routes/demo/presentkort'
import { Route as DemoPersonalRouteImport } from './routes/demo/personal'
import { Route as DemoMinSidaRouteImport } from './routes/demo/min-sida'
import { Route as DemoManifestRouteImport } from './routes/demo/manifest'
import { Route as DemoKanalerRouteImport } from './routes/demo/kanaler'
import { Route as DemoIncheckningRouteImport } from './routes/demo/incheckning'
import { Route as DemoGasterRouteImport } from './routes/demo/gaster'
import { Route as DemoGastRouteImport } from './routes/demo/gast'
import { Route as DemoFrukostRouteImport } from './routes/demo/frukost'
import { Route as DemoBokningarRouteImport } from './routes/demo/bokningar'
import { Route as DemoBokaRouteImport } from './routes/demo/boka'
import { Route as DemoAdminRouteImport } from './routes/demo/admin'
import { Route as BokaSlugRouteImport } from './routes/boka/$slug'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppMallarRouteImport } from './routes/app/mallar'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppKallorRouteImport } from './routes/app/kallor'
import { Route as AppInstallningarRouteImport } from './routes/app/installningar'
import { Route as AppBokningarRouteImport } from './routes/app/bokningar'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStadRoute = DemoStadRouteImport.update({
  id: '/stad',
  path: '/stad',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRapporterRoute = DemoRapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPresentkortRoute = DemoPresentkortRouteImport.update({
  id: '/presentkort',
  path: '/presentkort',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPersonalRoute = DemoPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => DemoRoute,
} as any)
const DemoMinSidaRoute = DemoMinSidaRouteImport.update({
  id: '/min-sida',
  path: '/min-sida',
  getParentRoute: () => DemoRoute,
} as any)
const DemoManifestRoute = DemoManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => DemoRoute,
} as any)
const DemoKanalerRoute = DemoKanalerRouteImport.update({
  id: '/kanaler',
  path: '/kanaler',
  getParentRoute: () => DemoRoute,
} as any)
const DemoIncheckningRoute = DemoIncheckningRouteImport.update({
  id: '/incheckning',
  path: '/incheckning',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGasterRoute = DemoGasterRouteImport.update({
  id: '/gaster',
  path: '/gaster',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGastRoute = DemoGastRouteImport.update({
  id: '/gast',
  path: '/gast',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFrukostRoute = DemoFrukostRouteImport.update({
  id: '/frukost',
  path: '/frukost',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBokningarRoute = DemoBokningarRouteImport.update({
  id: '/bokningar',
  path: '/bokningar',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBokaRoute = DemoBokaRouteImport.update({
  id: '/boka',
  path: '/boka',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DemoRoute,
} as any)
const BokaSlugRoute = BokaSlugRouteImport.update({
  id: '/boka/$slug',
  path: '/boka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMallarRoute = AppMallarRouteImport.update({
  id: '/mallar',
  path: '/mallar',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppKallorRoute = AppKallorRouteImport.update({
  id: '/kallor',
  path: '/kallor',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallningarRoute = AppInstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => AppRoute,
} as any)
const AppBokningarRoute = AppBokningarRouteImport.update({
  id: '/bokningar',
  path: '/bokningar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRouteWithChildren
  '/dpa': typeof DpaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/villkor': typeof VillkorRoute
  '/app/bokningar': typeof AppBokningarRoute
  '/app/installningar': typeof AppInstallningarRoute
  '/app/kallor': typeof AppKallorRoute
  '/app/login': typeof AppLoginRoute
  '/app/mallar': typeof AppMallarRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/boka/$slug': typeof BokaSlugRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/boka': typeof DemoBokaRoute
  '/demo/bokningar': typeof DemoBokningarRoute
  '/demo/frukost': typeof DemoFrukostRoute
  '/demo/gast': typeof DemoGastRoute
  '/demo/gaster': typeof DemoGasterRoute
  '/demo/incheckning': typeof DemoIncheckningRoute
  '/demo/kanaler': typeof DemoKanalerRoute
  '/demo/manifest': typeof DemoManifestRoute
  '/demo/min-sida': typeof DemoMinSidaRoute
  '/demo/personal': typeof DemoPersonalRoute
  '/demo/presentkort': typeof DemoPresentkortRoute
  '/demo/rapporter': typeof DemoRapporterRoute
  '/demo/stad': typeof DemoStadRoute
  '/g/$token': typeof GTokenRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/villkor': typeof VillkorRoute
  '/app/bokningar': typeof AppBokningarRoute
  '/app/installningar': typeof AppInstallningarRoute
  '/app/kallor': typeof AppKallorRoute
  '/app/login': typeof AppLoginRoute
  '/app/mallar': typeof AppMallarRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/boka/$slug': typeof BokaSlugRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/boka': typeof DemoBokaRoute
  '/demo/bokningar': typeof DemoBokningarRoute
  '/demo/frukost': typeof DemoFrukostRoute
  '/demo/gast': typeof DemoGastRoute
  '/demo/gaster': typeof DemoGasterRoute
  '/demo/incheckning': typeof DemoIncheckningRoute
  '/demo/kanaler': typeof DemoKanalerRoute
  '/demo/manifest': typeof DemoManifestRoute
  '/demo/min-sida': typeof DemoMinSidaRoute
  '/demo/personal': typeof DemoPersonalRoute
  '/demo/presentkort': typeof DemoPresentkortRoute
  '/demo/rapporter': typeof DemoRapporterRoute
  '/demo/stad': typeof DemoStadRoute
  '/g/$token': typeof GTokenRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRouteWithChildren
  '/dpa': typeof DpaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/villkor': typeof VillkorRoute
  '/app/bokningar': typeof AppBokningarRoute
  '/app/installningar': typeof AppInstallningarRoute
  '/app/kallor': typeof AppKallorRoute
  '/app/login': typeof AppLoginRoute
  '/app/mallar': typeof AppMallarRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/boka/$slug': typeof BokaSlugRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/boka': typeof DemoBokaRoute
  '/demo/bokningar': typeof DemoBokningarRoute
  '/demo/frukost': typeof DemoFrukostRoute
  '/demo/gast': typeof DemoGastRoute
  '/demo/gaster': typeof DemoGasterRoute
  '/demo/incheckning': typeof DemoIncheckningRoute
  '/demo/kanaler': typeof DemoKanalerRoute
  '/demo/manifest': typeof DemoManifestRoute
  '/demo/min-sida': typeof DemoMinSidaRoute
  '/demo/personal': typeof DemoPersonalRoute
  '/demo/presentkort': typeof DemoPresentkortRoute
  '/demo/rapporter': typeof DemoRapporterRoute
  '/demo/stad': typeof DemoStadRoute
  '/g/$token': typeof GTokenRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cookies'
    | '/demo'
    | '/dpa'
    | '/integritetspolicy'
    | '/villkor'
    | '/app/bokningar'
    | '/app/installningar'
    | '/app/kallor'
    | '/app/login'
    | '/app/mallar'
    | '/app/onboarding'
    | '/boka/$slug'
    | '/demo/admin'
    | '/demo/boka'
    | '/demo/bokningar'
    | '/demo/frukost'
    | '/demo/gast'
    | '/demo/gaster'
    | '/demo/incheckning'
    | '/demo/kanaler'
    | '/demo/manifest'
    | '/demo/min-sida'
    | '/demo/personal'
    | '/demo/presentkort'
    | '/demo/rapporter'
    | '/demo/stad'
    | '/g/$token'
    | '/app/'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/dpa'
    | '/integritetspolicy'
    | '/villkor'
    | '/app/bokningar'
    | '/app/installningar'
    | '/app/kallor'
    | '/app/login'
    | '/app/mallar'
    | '/app/onboarding'
    | '/boka/$slug'
    | '/demo/admin'
    | '/demo/boka'
    | '/demo/bokningar'
    | '/demo/frukost'
    | '/demo/gast'
    | '/demo/gaster'
    | '/demo/incheckning'
    | '/demo/kanaler'
    | '/demo/manifest'
    | '/demo/min-sida'
    | '/demo/personal'
    | '/demo/presentkort'
    | '/demo/rapporter'
    | '/demo/stad'
    | '/g/$token'
    | '/app'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cookies'
    | '/demo'
    | '/dpa'
    | '/integritetspolicy'
    | '/villkor'
    | '/app/bokningar'
    | '/app/installningar'
    | '/app/kallor'
    | '/app/login'
    | '/app/mallar'
    | '/app/onboarding'
    | '/boka/$slug'
    | '/demo/admin'
    | '/demo/boka'
    | '/demo/bokningar'
    | '/demo/frukost'
    | '/demo/gast'
    | '/demo/gaster'
    | '/demo/incheckning'
    | '/demo/kanaler'
    | '/demo/manifest'
    | '/demo/min-sida'
    | '/demo/personal'
    | '/demo/presentkort'
    | '/demo/rapporter'
    | '/demo/stad'
    | '/g/$token'
    | '/app/'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DemoRoute: typeof DemoRouteWithChildren
  DpaRoute: typeof DpaRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  VillkorRoute: typeof VillkorRoute
  BokaSlugRoute: typeof BokaSlugRoute
  GTokenRoute: typeof GTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stad': {
      id: '/demo/stad'
      path: '/stad'
      fullPath: '/demo/stad'
      preLoaderRoute: typeof DemoStadRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/rapporter': {
      id: '/demo/rapporter'
      path: '/rapporter'
      fullPath: '/demo/rapporter'
      preLoaderRoute: typeof DemoRapporterRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/presentkort': {
      id: '/demo/presentkort'
      path: '/presentkort'
      fullPath: '/demo/presentkort'
      preLoaderRoute: typeof DemoPresentkortRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/personal': {
      id: '/demo/personal'
      path: '/personal'
      fullPath: '/demo/personal'
      preLoaderRoute: typeof DemoPersonalRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/min-sida': {
      id: '/demo/min-sida'
      path: '/min-sida'
      fullPath: '/demo/min-sida'
      preLoaderRoute: typeof DemoMinSidaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/manifest': {
      id: '/demo/manifest'
      path: '/manifest'
      fullPath: '/demo/manifest'
      preLoaderRoute: typeof DemoManifestRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/kanaler': {
      id: '/demo/kanaler'
      path: '/kanaler'
      fullPath: '/demo/kanaler'
      preLoaderRoute: typeof DemoKanalerRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/incheckning': {
      id: '/demo/incheckning'
      path: '/incheckning'
      fullPath: '/demo/incheckning'
      preLoaderRoute: typeof DemoIncheckningRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/gaster': {
      id: '/demo/gaster'
      path: '/gaster'
      fullPath: '/demo/gaster'
      preLoaderRoute: typeof DemoGasterRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/gast': {
      id: '/demo/gast'
      path: '/gast'
      fullPath: '/demo/gast'
      preLoaderRoute: typeof DemoGastRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/frukost': {
      id: '/demo/frukost'
      path: '/frukost'
      fullPath: '/demo/frukost'
      preLoaderRoute: typeof DemoFrukostRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/bokningar': {
      id: '/demo/bokningar'
      path: '/bokningar'
      fullPath: '/demo/bokningar'
      preLoaderRoute: typeof DemoBokningarRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/boka': {
      id: '/demo/boka'
      path: '/boka'
      fullPath: '/demo/boka'
      preLoaderRoute: typeof DemoBokaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/admin': {
      id: '/demo/admin'
      path: '/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof DemoRoute
    }
    '/boka/$slug': {
      id: '/boka/$slug'
      path: '/boka/$slug'
      fullPath: '/boka/$slug'
      preLoaderRoute: typeof BokaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mallar': {
      id: '/app/mallar'
      path: '/mallar'
      fullPath: '/app/mallar'
      preLoaderRoute: typeof AppMallarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kallor': {
      id: '/app/kallor'
      path: '/kallor'
      fullPath: '/app/kallor'
      preLoaderRoute: typeof AppKallorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/installningar': {
      id: '/app/installningar'
      path: '/installningar'
      fullPath: '/app/installningar'
      preLoaderRoute: typeof AppInstallningarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bokningar': {
      id: '/app/bokningar'
      path: '/bokningar'
      fullPath: '/app/bokningar'
      preLoaderRoute: typeof AppBokningarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBokningarRoute: typeof AppBokningarRoute
  AppInstallningarRoute: typeof AppInstallningarRoute
  AppKallorRoute: typeof AppKallorRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMallarRoute: typeof AppMallarRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBokningarRoute: AppBokningarRoute,
  AppInstallningarRoute: AppInstallningarRoute,
  AppKallorRoute: AppKallorRoute,
  AppLoginRoute: AppLoginRoute,
  AppMallarRoute: AppMallarRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAdminRoute: typeof DemoAdminRoute
  DemoBokaRoute: typeof DemoBokaRoute
  DemoBokningarRoute: typeof DemoBokningarRoute
  DemoFrukostRoute: typeof DemoFrukostRoute
  DemoGastRoute: typeof DemoGastRoute
  DemoGasterRoute: typeof DemoGasterRoute
  DemoIncheckningRoute: typeof DemoIncheckningRoute
  DemoKanalerRoute: typeof DemoKanalerRoute
  DemoManifestRoute: typeof DemoManifestRoute
  DemoMinSidaRoute: typeof DemoMinSidaRoute
  DemoPersonalRoute: typeof DemoPersonalRoute
  DemoPresentkortRoute: typeof DemoPresentkortRoute
  DemoRapporterRoute: typeof DemoRapporterRoute
  DemoStadRoute: typeof DemoStadRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAdminRoute: DemoAdminRoute,
  DemoBokaRoute: DemoBokaRoute,
  DemoBokningarRoute: DemoBokningarRoute,
  DemoFrukostRoute: DemoFrukostRoute,
  DemoGastRoute: DemoGastRoute,
  DemoGasterRoute: DemoGasterRoute,
  DemoIncheckningRoute: DemoIncheckningRoute,
  DemoKanalerRoute: DemoKanalerRoute,
  DemoManifestRoute: DemoManifestRoute,
  DemoMinSidaRoute: DemoMinSidaRoute,
  DemoPersonalRoute: DemoPersonalRoute,
  DemoPresentkortRoute: DemoPresentkortRoute,
  DemoRapporterRoute: DemoRapporterRoute,
  DemoStadRoute: DemoStadRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DemoRoute: DemoRouteWithChildren,
  DpaRoute: DpaRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  VillkorRoute: VillkorRoute,
  BokaSlugRoute: BokaSlugRoute,
  GTokenRoute: GTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
